/**
 * ──────────────────────────────────────────────────────────────────
 * 🏢 Company Name: Bonifade Technologies
 * 👨‍💻 Developer: Bowofade Oyerinde
 * 🐙 GitHub: oyenet1
 * 📅 Created Date: 2026-04-05
 * 🔄 Updated Date: 2026-04-05
 * ──────────────────────────────────────────────────────────────────
 */

import { writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import fg from 'fast-glob'
import { generateHeader } from '../header-generator.js'

const green = (s: string) => `\x1b[32m${s}\x1b[0m`
const bold = (s: string) => `\x1b[1m${s}\x1b[0m`

const BARREL_PATH = join(process.cwd(), 'src', 'db', 'schema.ts')

/**
 * `vono schema:sync`
 *
 * Scans all `*.schema.ts` files under `src/modules/` and regenerates
 * `src/db/schema.ts` as a re-export barrel.
 */
export async function runSchemaSync(_args: string[]): Promise<void> {
  const modulesDir = join(process.cwd(), 'src', 'modules')
  const pattern = join(modulesDir, '**/*.schema.ts').replace(/\\/g, '/')

  const schemaFiles = await fg(pattern, {
    absolute: true,
    ignore: ['**/node_modules/**', '**/dist/**'],
  })

  if (schemaFiles.length === 0) {
    process.stdout.write(`No *.schema.ts files found under src/modules/ — barrel unchanged.\n`)
    return
  }

  const barrelDir = join(process.cwd(), 'src', 'db')
  const exports = schemaFiles
    .sort()
    .map((filePath) => {
      // Compute relative path from src/db/ to the schema file
      const rel = relative(barrelDir, filePath).replace(/\\/g, '/').replace(/\.ts$/, '.js')
      return `export * from '${rel.startsWith('.') ? rel : './' + rel}'`
    })
    .join('\n')

  const header = generateHeader(BARREL_PATH)
  const content = `${header}\n\n// Auto-generated by \`vono schema:sync\` — do not edit manually.\n// Re-run \`vono schema:sync\` after adding or removing schema files.\n\n${exports}\n`

  writeFileSync(BARREL_PATH, content, 'utf8')

  process.stdout.write(
    `${bold('schema:sync')} — regenerated ${green(BARREL_PATH)} with ${schemaFiles.length} schema${schemaFiles.length === 1 ? '' : 's'}.\n`,
  )
}
